// index.js
//
// MCP server for the AusPost fleet telemetry hackathon demo.
// Wraps the fleet context engine (context-engine.js) as MCP tools, so
// Claude Desktop / Claude Code can query fleet state directly and answer
// questions the same way the Safety / Delivery / Maintenance dashboards
// do - but conversationally.
//
// context-engine.js automatically uses the REAL Confluent Cloud + Flink +
// Bedrock pipeline if the required environment variables are set (see
// SETUP.md - get them with `terraform output` from the terraform/
// directory), and falls back to an in-memory simulator otherwise.
//
// Run it:
//   npm install
//   npm start
//
// Then point Claude Desktop or Claude Code at it (see SETUP.md).

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import { contextEngine, isLive } from './context-engine.js';
import { startHttpServer } from './http-server.js';
import { startTelemetrySimulator } from './telemetry-simulator.js';

console.error(`[fleet-context-engine] mode: ${isLive ? 'LIVE (real Confluent Cloud + Flink + Bedrock)' : 'SIMULATED (in-memory, no Confluent Cloud env vars found)'}`);

// Also expose the same context engine over a small JSON API, so
// fleet-intelligence-console.html (a static HTML file that can't safely
// hold Confluent Cloud credentials) can poll for real data too. Set
// HTTP_API=false to disable if you only want the MCP stdio server.
if (process.env.HTTP_API !== 'false') {
  startHttpServer();
}

// In LIVE mode, the real topics are otherwise a one-shot seeded batch -
// this keeps real data flowing continuously so the console has something
// new to show between demo-button clicks. SIMULATED mode already ticks
// its own in-memory state on an interval, so it doesn't need this.
if (isLive) {
  startTelemetrySimulator();
}

const server = new McpServer({
  name: 'fleet-context-engine',
  version: '1.0.0',
});

function textResult(data) {
  return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }] };
}

function tool(name, description, schema, handler) {
  server.tool(name, description, schema, async (args) => {
    try {
      return textResult(await handler(args));
    } catch (err) {
      return textResult({ error: err.message });
    }
  });
}

tool(
  'get_fleet_summary',
  'Get a live one-screen summary of the whole fleet: vehicles online, average speed/engine temp/fuel level, and how many vehicles are currently flagged as high risk for safety or maintenance.',
  {},
  async () => contextEngine.getFleetSummary()
);

tool(
  'get_vehicle',
  'Get the current live telemetry and risk scores for one specific vehicle by ID (e.g. "VH-1004").',
  { vehicleId: z.string().describe('Vehicle ID, e.g. VH-1004') },
  async ({ vehicleId }) => {
    const v = await contextEngine.getVehicle(vehicleId);
    return v ?? { error: `No vehicle found with ID ${vehicleId}` };
  }
);

tool(
  'list_vehicles',
  'List every vehicle currently reporting telemetry, with their live speed, engine temp, and risk scores.',
  {},
  async () => contextEngine.listVehicles()
);

tool(
  'list_high_risk_vehicles',
  'List vehicles currently above the risk threshold (risk > 70), optionally filtered to just "safety" (driver risk) or "maintenance" risk. Omit domain to get both.',
  { domain: z.enum(['safety', 'maintenance', 'all']).optional().describe('Which risk type to filter on. Defaults to all.') },
  async ({ domain }) => contextEngine.listHighRisk(domain === 'all' ? undefined : domain)
);

tool(
  'get_recent_recommendations',
  'Get the most recent AI-generated recommendations (the same ones published to ai.safety.recommendations, ai.delivery.recommendations, and ai.maintenance.recommendations - generated by the real Bedrock-backed Flink model when running in live mode), optionally filtered by business domain.',
  {
    domain: z.enum(['safety', 'delivery', 'maintenance']).optional().describe('Filter to one business domain. Omit for all.'),
    limit: z.number().int().min(1).max(50).optional().describe('Max number of recommendations to return. Defaults to 10.'),
  },
  async ({ domain, limit }) => contextEngine.getRecentRecommendations(domain, limit ?? 10)
);

tool(
  'inject_demo_incident',
  'DEMO: raise a vehicle\'s engine temperature to trigger safety, delivery, and maintenance recommendations. In live mode this produces a REAL wire-encoded record to the real vehicle.telemetry topic, so the real Flink pipeline and Bedrock model react to it for real (allow it a few seconds/minutes to process before checking get_recent_recommendations). In simulated mode it just updates in-memory state instantly.',
  { vehicleId: z.string().optional().describe('Vehicle ID to spike. Omit to pick one at random.') },
  async ({ vehicleId }) => contextEngine.injectIncident(vehicleId)
);

tool(
  'get_weather',
  'Get current weather conditions for one geozone (e.g. "docklands-cbd"), or for all geozones if none is given. Useful for explaining why driver risk or delivery delays are elevated in a given area.',
  { geozone: z.string().optional().describe('Geozone ID, e.g. docklands-cbd. Omit for all geozones.') },
  async ({ geozone }) => contextEngine.getWeather(geozone)
);

tool(
  'get_traffic_incidents',
  'Get recent traffic incidents (congestion, road closures, collisions, roadworks), optionally filtered to one geozone.',
  {
    geozone: z.string().optional().describe('Geozone ID to filter on. Omit for all geozones.'),
    limit: z.number().int().min(1).max(50).optional().describe('Max incidents to return. Defaults to 10.'),
  },
  async ({ geozone, limit }) => contextEngine.getTrafficIncidents(geozone, limit ?? 10)
);

tool(
  'get_parcel_volume',
  'Get recent parcel-onboard counts (a proxy for delivery load/capacity), optionally filtered to one vehicle.',
  {
    vehicleId: z.string().optional().describe('Vehicle ID to filter on. Omit for the whole fleet log.'),
    limit: z.number().int().min(1).max(50).optional().describe('Max entries to return. Defaults to 10.'),
  },
  async ({ vehicleId, limit }) => contextEngine.getParcelVolume(vehicleId, limit ?? 10)
);

tool(
  'inject_demo_traffic_incident',
  'DEMO: raise a high-severity traffic incident in a geozone on demand, to show the delivery-rerouting recommendation path without waiting for it to happen randomly. In live mode this produces a REAL record to the real traffic.incidents topic.',
  { geozone: z.string().optional().describe('Geozone ID to raise the incident in. Omit to pick one at random.') },
  async ({ geozone }) => contextEngine.injectTrafficIncident(geozone)
);

const transport = new StdioServerTransport();
await server.connect(transport);
